// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const DATABASE_URL = `postgresql://${env("DB_USER")}:${env("DB_PASS")}@${env("DB_HOST")}:${env("DB_PORT")}/${env("DB_NAME")}?schema=public`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
